apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-add-tasks-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-add-tasks-api
  template:
    metadata:
      labels:
        app: todo-add-tasks-api
    spec:
      containers:
      - name: todo-add-tasks-api
        image: blibacr4829.azurecr.io/todo-add-tasks-api:v1
        ports:
        - containerPort: 8000
        env: 
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:blib-sqlserver.database.windows.net,1433;Database=blib-db;Uid=tani;Pwd=Sql@Admin#8974;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"        
