apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-add-tasks-api-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
    - host: add-task-api.tanishka.store
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: todo-add-tasks-api
                port:
                  number: 80
